language: php

php:
  - 5.4
  - 5.5
  - 5.6
  - hhvm

before_script:
  - composer install --dev --prefer-source
  - sudo apt-get install nginx
  - sudo cp .travis.nginx.conf /etc/nginx/nginx.conf
  - sudo /etc/init.d/nginx restart


script:
  - ./vendor/bin/phpunit
